import React from "react";
import Head from "next/head";
import Image from "next/image";
import Footer from "@/components/Footer/Footer";
import Navbar from "@/components/Navbar/Navbar";
import curve1 from "@/public/assets/curve1.png";
import curve2 from "@/public/assets/curve2.png";
import curve3 from "@/public/assets/curve3.png";
import curve4 from "@/public/assets/curve4.jpg";
import { Video3 } from "@/components/Livepeer";
import Link from "next/link";

function BitcoinLiquidityPools() {
  const [show, setShow] = React.useState(false);
  const onClick = () => setShow(!show);

  return (
    <>
    <Head>
        <title>Bitcoin Liquidity Pools | HyperFi</title>
        <meta name="description" content="Explore Bitcoin liquidity pools on Citrea's zkEVM Layer 2" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Navbar />
      
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
        {/* Hero Section */}
        <div className="text-center mb-20">
          <h1 className="text-4xl md:text-6xl font-extrabold text-white mb-6 bg-gradient-to-r from-orange-400 to-yellow-600 bg-clip-text text-transparent">
            Bitcoin Liquidity Pools
          </h1>
          <p className="text-xl text-gray-300 max-w-3xl mx-auto">
            Provide liquidity to Bitcoin trading pairs and earn fees from trades.
            All powered by Citrea's zkEVM Layer 2 for Bitcoin.
          </p>
        </div>
        
        {/* Section 1: What are Bitcoin Liquidity Pools */}
        <div className="mb-24">
          <div className="flex flex-col md:flex-row items-center gap-8 md:gap-16">
            <div className="md:w-1/2">
              <h2 className="text-3xl md:text-4xl font-bold text-white mb-6">
                What are Bitcoin Liquidity Pools?
              </h2>
              <p className="text-gray-300 text-lg mb-6">
                Liquidity pools are collections of funds locked in smart contracts that facilitate trading by providing 
                liquidity to decentralized exchanges. With Citrea's zkEVM Layer 2, Bitcoin holders can now participate 
                in these pools directly with their BTC.
              </p>
              <p className="text-gray-300 text-lg mb-6">
                Traditional Bitcoin has limited programmability for such applications. Citrea's zkEVM brings 
                sophisticated liquidity pool functionality directly to Bitcoin holders without wrapping or bridging.
              </p>
              <div className="bg-black rounded-lg p-6 border-l-4 border-yellow-500">
                <h3 className="text-xl font-semibold text-white mb-2">Why Provide Liquidity?</h3>
                <p className="text-gray-300">
                  By providing liquidity, you earn a portion of the trading fees generated by the pool. This creates 
                  a passive income stream from your Bitcoin holdings while supporting the DeFi ecosystem.
            </p>
              </div>
            </div>
            <div className="md:w-1/2">
              <div className="relative rounded-2xl overflow-hidden shadow-2xl">
              <Image
                src={curve1.src}
                  alt="Bitcoin Liquidity Pools"
                  width={600}
                  height={400}
                  className="object-cover w-full h-[400px] rounded-2xl"
                />
                <div className="absolute inset-0 bg-gradient-to-t from-black to-transparent opacity-60"></div>
              </div>
            </div>
          </div>
        </div>

        {/* Section 2: How Bitcoin Liquidity Pools Work on Citrea */}
        <div className="mb-24">
          <div className="flex flex-col md:flex-row-reverse items-center gap-8 md:gap-16">
            <div className="md:w-1/2">
              <h2 className="text-3xl md:text-4xl font-bold text-white mb-6">
                How Bitcoin Liquidity Pools Work on Citrea
              </h2>
              <p className="text-gray-300 text-lg mb-6">
                Citrea's zkEVM Layer 2 solution enables sophisticated automated market makers (AMMs) while inheriting 
                Bitcoin's security. This creates efficient, low-fee trading for Bitcoin pairs.
              </p>
              <div className="grid grid-cols-1 gap-4 mb-6">
                <div className="bg-black p-5 rounded-lg">
                  <h3 className="text-xl font-semibold text-white mb-2">Provide Liquidity</h3>
                  <p className="text-gray-300">
                    Deposit your BTC along with another asset to create a trading pair. You'll receive LP tokens 
                    representing your share of the pool.
                  </p>
                </div>
                <div className="bg-black p-5 rounded-lg">
                  <h3 className="text-xl font-semibold text-white mb-2">Earn Trading Fees</h3>
                  <p className="text-gray-300">
                    Each trade in the pool generates a fee (typically 0.3%), which is distributed proportionally 
                    to all liquidity providers.
                  </p>
                </div>
                <div className="bg-gray-800 p-5 rounded-lg">
                  <h3 className="text-xl font-semibold text-white mb-2">Constant Product Formula</h3>
                  <p className="text-gray-300">
                    Pools use the x*y=k formula to maintain balance. As one asset is bought, its price increases 
                    relative to the other asset.
                  </p>
                </div>
              </div>
            </div>
            <div className="md:w-1/2">
              <div className="relative rounded-2xl overflow-hidden shadow-2xl">
              <Image
                src={curve2.src}
                  alt="How Bitcoin Liquidity Pools Work"
                  width={600}
                  height={400}
                  className="object-cover w-full h-[400px] rounded-2xl"
                />
                <div className="absolute inset-0 bg-gradient-to-t from-black to-transparent opacity-60"></div>
              </div>
            </div>
          </div>
        </div>

        {/* Section 3: Bitcoin Liquidity Pool Types */}
        <div className="mb-24">
          <h2 className="text-3xl md:text-4xl font-bold text-white mb-10 text-center">
            Bitcoin Liquidity Pool Types
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            <div className="bg-gray-800 rounded-xl p-6 shadow-lg">
              <div className="w-12 h-12 bg-yellow-500 rounded-full flex items-center justify-center mb-4">
                <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 6l3 1m0 0l-3 9a5.002 5.002 0 006.001 0M6 7l3 9M6 7l6-2m6 2l3-1m-3 1l-3 9a5.002 5.002 0 006.001 0M18 7l3 9m-3-9l-6-2m0-2v2m0 16V5m0 16H9m3 0h3" />
                </svg>
              </div>
              <h3 className="text-xl font-bold text-white mb-3">Standard Pools</h3>
              <p className="text-gray-300">
                Basic 50/50 weighted pools like BTC-USDC or BTC-ETH. These are the most common and straightforward 
                pools, suitable for beginners.
              </p>
            </div>
            
            <div className="bg-gray-800 rounded-xl p-6 shadow-lg">
              <div className="w-12 h-12 bg-yellow-500 rounded-full flex items-center justify-center mb-4">
                <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z" />
                </svg>
              </div>
              <h3 className="text-xl font-bold text-white mb-3">Stable Pools</h3>
              <p className="text-gray-300">
                Specialized pools for stablecoins and wrapped Bitcoin variants that minimize slippage and 
                maximize capital efficiency for similar-valued assets.
              </p>
            </div>
            
            <div className="bg-gray-800 rounded-xl p-6 shadow-lg">
              <div className="w-12 h-12 bg-yellow-500 rounded-full flex items-center justify-center mb-4">
                <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M11 3.055A9.001 9.001 0 1020.945 13H11V3.055z" />
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M20.488 9H15V3.512A9.025 9.025 0 0120.488 9z" />
                </svg>
              </div>
              <h3 className="text-xl font-bold text-white mb-3">Weighted Pools</h3>
              <p className="text-gray-300">
                Custom-weighted pools that allow for different proportions of assets, such as 80% BTC and 20% 
                stablecoin for reduced impermanent loss.
              </p>
            </div>
          </div>
        </div>
        
        {/* Section 4: Benefits and Risks */}
        <div className="mb-24">
          <div className="flex flex-col md:flex-row items-center gap-8 md:gap-16">
            <div className="md:w-1/2">
              <h2 className="text-3xl md:text-4xl font-bold text-white mb-6">
                Benefits and Risks
              </h2>
              
              <div className="mb-8">
                <h3 className="text-2xl font-semibold text-white mb-4">Benefits</h3>
                <ul className="space-y-3">
                  <li className="flex gap-3">
                    <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6 text-green-500 flex-shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                    </svg>
                    <span className="text-gray-300">Earn passive income from trading fees (typically 0.3% per trade)</span>
                  </li>
                  <li className="flex gap-3">
                    <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6 text-green-500 flex-shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                    </svg>
                    <span className="text-gray-300">Support the Bitcoin DeFi ecosystem by providing necessary liquidity</span>
                  </li>
                  <li className="flex gap-3">
                    <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6 text-green-500 flex-shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                    </svg>
                    <span className="text-gray-300">Potential for additional incentives through liquidity mining programs</span>
                  </li>
                </ul>
              </div>
              
              <div>
                <h3 className="text-2xl font-semibold text-white mb-4">Risks</h3>
                <ul className="space-y-3">
                  <li className="flex gap-3">
                    <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6 text-red-500 flex-shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
                    </svg>
                    <span className="text-gray-300">Impermanent loss when asset prices change relative to each other</span>
                  </li>
                  <li className="flex gap-3">
                    <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6 text-red-500 flex-shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
                    </svg>
                    <span className="text-gray-300">Smart contract risks, though mitigated by Citrea's security model</span>
                  </li>
                  <li className="flex gap-3">
                    <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6 text-red-500 flex-shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
                    </svg>
                    <span className="text-gray-300">Market volatility affecting the value of your pooled assets</span>
                  </li>
                </ul>
              </div>
            </div>
            <div className="md:w-1/2">
              <div className="relative rounded-2xl overflow-hidden shadow-2xl">
              <Image
                src={curve3.src}
                  alt="Bitcoin Liquidity Pool Benefits and Risks"
                  width={600}
                  height={400}
                  className="object-cover w-full h-[500px] rounded-2xl"
                />
                <div className="absolute inset-0 bg-gradient-to-t from-black to-transparent opacity-60"></div>
              </div>
            </div>
          </div>
        </div>

        {/* Video Section */}
        <div className="mb-24">
          <h2 className="text-3xl md:text-4xl font-bold text-white mb-6 text-center">
            Learn About Bitcoin Liquidity Pools
          </h2>
          <p className="text-gray-300 text-lg mb-10 text-center max-w-3xl mx-auto">
            Watch our explainer video to understand how Bitcoin liquidity pools work on Citrea's zkEVM Layer 2
          </p>
          <div className="w-full max-w-4xl mx-auto rounded-2xl overflow-hidden shadow-2xl">
            <div className="aspect-w-16 aspect-h-9" onClick={onClick}>
              <Video3 />
            </div>
          </div>
        </div>
        
        {/* CTA Section */}
        <div className="bg-gradient-to-r from-gray-800 to-gray-900 rounded-2xl p-8 md:p-12 shadow-2xl">
          <div className="flex flex-col md:flex-row items-center justify-between">
            <div className="md:w-2/3 mb-8 md:mb-0">
              <h2 className="text-3xl font-bold text-white mb-4">Ready to Provide Bitcoin Liquidity?</h2>
              <p className="text-gray-300 text-lg">
                Connect your wallet and start earning fees by providing liquidity to Bitcoin pools on HyperFi.
              </p>
            </div>
            <div>
              <button className="px-8 py-4 bg-gradient-to-r from-yellow-500 to-orange-500 hover:from-yellow-600 hover:to-orange-600 text-white font-bold rounded-lg shadow-lg transition-all duration-300">
                Connect Wallet
              </button>
            </div>
          </div>
      </div>
      </div>
      
      <Footer />
    </>
  );
}

export default BitcoinLiquidityPools;
